-- Create table

CREATE TABLE color (
    color_id INT GENERATED ALWAYS AS IDENTITY,
    color_name VARCHAR NOT NULL
);

-- insert data
INSERT INTO color(color_name)
VALUES ('Red');

SELECT * FROM color;

-- Below query will fire an error becuase GENERATED ALWAYS doesn't allow any external/user-define value.
INSERT INTO color (color_id, color_name)
VALUES (2, 'Green');

-- above error can be resolve using OVERRIDING SYSTEM VALUE 
INSERT INTO color (color_id, color_name)
OVERRIDING SYSTEM VALUE 
VALUES(2, 'Green');

-- GENERATED BY DEFAULT clause allows insert/update over identity column.

